// Code generated by mockery v2.9.4. DO NOT EDIT.

package mocks

import (
	ctx "github.com/x-xyz/goapi/base/ctx"
	domain "github.com/x-xyz/goapi/domain"

	mock "github.com/stretchr/testify/mock"
)

// PayTokenRepo is an autogenerated mock type for the PayTokenRepo type
type PayTokenRepo struct {
	mock.Mock
}

// Create provides a mock function with given fields: _a0, _a1
func (_m *PayTokenRepo) Create(_a0 ctx.Ctx, _a1 *domain.PayToken) error {
	ret := _m.Called(_a0, _a1)

	var r0 error
	if rf, ok := ret.Get(0).(func(ctx.Ctx, *domain.PayToken) error); ok {
		r0 = rf(_a0, _a1)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// FindOne provides a mock function with given fields: _a0, _a1, _a2
func (_m *PayTokenRepo) FindOne(_a0 ctx.Ctx, _a1 domain.ChainId, _a2 domain.Address) (*domain.PayToken, error) {
	ret := _m.Called(_a0, _a1, _a2)

	var r0 *domain.PayToken
	if rf, ok := ret.Get(0).(func(ctx.Ctx, domain.ChainId, domain.Address) *domain.PayToken); ok {
		r0 = rf(_a0, _a1, _a2)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*domain.PayToken)
		}
	}

	var r1 error
	if rf, ok := ret.Get(1).(func(ctx.Ctx, domain.ChainId, domain.Address) error); ok {
		r1 = rf(_a0, _a1, _a2)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// Upsert provides a mock function with given fields: _a0, _a1
func (_m *PayTokenRepo) Upsert(_a0 ctx.Ctx, _a1 *domain.PayToken) error {
	ret := _m.Called(_a0, _a1)

	var r0 error
	if rf, ok := ret.Get(0).(func(ctx.Ctx, *domain.PayToken) error); ok {
		r0 = rf(_a0, _a1)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}
