package domain

// Table Maps to mongo collection
type Table string

const (
	TableCollections               Table = "collections"
	TableCollectionRegistrations   Table = "collectionregistrations"
	TableFollows                   Table = "follows"
	TableERC721Contracts           Table = "erc721contracts"
	TableNotificationSettings      Table = "notificationsettings"
	TableNFTItems                  Table = "nftitems"
	TableLiks                      Table = "likes"
	TableCollectionLiks            Table = "collectionLikes"
	TableCategories                Table = "categories"
	TableERC1155Holdings           Table = "erc1155holdings"
	TableUnlockableContents        Table = "unlockablecontents"
	TablePayTokens                 Table = "paytokens"
	TableAccounts                  Table = "accounts"
	TableDisableExploreCollections Table = "disabledexplorercollections"
	TableERC1155Contracts          Table = "erc1155contracts"
	TableModerators                Table = "moderators"
	TableTrackerStates             Table = "tracker_states"
	TableBlocks                    Table = "blocks"
	TableAirdrops                  Table = "airdrops"
	TableProofs                    Table = "proofs"
	TableTradingVolumes            Table = "tradingVolumes"
	TableActivityHistories         Table = "activityHistories"
	TableOpenseaData               Table = "openseaData"
	TableVexFeeDistributionHistory Table = "vexFeeDistributionHistory"
	TableFolders                   Table = "folders"
	TableFolderNftRelationships    Table = "folderNftRelationships"
	TableFloorPriceHistories       Table = "floorPriceHistories"
	TablePromotions                Table = "promotions"
	TableCollPromotions            Table = "collection_promotions"
	TableListingRecords            Table = "listing_records"
	TableOrderItems                Table = "orderItems"
	TableOrders                    Table = "orders"
	TableOrderNonces               Table = "orderNonces"
	TableExternalListing           Table = "externalListings"
	TableStatistics                Table = "statistics"
	TableIpListings                Table = "ipListings"
	TableApeStakings               Table = "apecoinStakings"
	TableTwelvefold                Table = "twelvefold"
)
